### ISSUE TITLE
Configuration fatigue

### ISSUE THREAD

**Issue by laowantong** [poponealex/APSecurity#1]
I'm afraid that inputting each and every configuration parameter is going to get boring very quickly, especially since there is no default value. What about letting the user modify directly a configuration file pre-populated with sensible default values? Or accepting these parameters as command line arguments (again, with sensible default values)? You should give [docopt](https://docopt.readthedocs.io/en/latest/) a try, it's great.

**Comment by poponealex** [comment]
That's what I did at first, although I wanted to enhance the user experience by having the option to input the parameters and get validation. Perhaps you're right, it could make the process tedious rather than intuitive. I could upload an alternative configuration file for the user to modify directly. Anyhow, after that all the parameters are entered and the file has been run, a `.json` file will be generated with an object containing all the entered parameters. This `.json` file will be used by the program for each use, you do not have to entered the configuration setting over and over again, only once except if you need to change a parameter.
Thanks for the tip, I'll take a look at it!

**Comment by laowantong** [comment]
No problem indeed if the user can modify the JSON file afterwards.

**Comment by poponealex** [comment]
The user could indeed modify the JSON file afterwards or run `config.py` again to generate a new JSON file, which would overwrite the previous one, with the newly added parameters.
